server:
  port: 8090

logging:
  level:
    org:
      springframework:
        web: DEBUG
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Hondacity*1
    url: jdbc:mysql://localhost:3306/registrationdb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
  show-sql: true